export type EditorialSourceType =
  | "locked-app-copy"
  | "approved-editorial-library"
  | "approved-marketing-copy"
  | "founder-approved-explanatory-copy"
  | "frozen-product-terminology";

export type EditorialContentRecord = {
  id: string;
  exactText: string;
  sourceType: EditorialSourceType;
  sourceReference: string;
  approvalStatus: "approved" | "requires-editorial-approval";
  placement: string;
  illustrative: boolean;
};

/**
 * Founder-approved website content governance:
 *
 * This library explains the product; it does not mirror personalised app
 * output. Home, the Canopy introduction and Weekly Letter, Curiosities,
 * Thinkers, Create, all of Within (including Pause), and Privacy & Trust are
 * intentionally static. Do not connect those records to app assignments,
 * generated observations, or any other live editorial feed.
 *
 * Family Rhythms is the sole weekly editorial surface. Its Dinner Table
 * Conversation, Do This Together, and One Thing Worth Talking About records
 * form one indivisible published edition: they may update once per week only,
 * always together, and never through independent or partial rotation.
 */

export const homeContent = [
  { id: "home-aaj-kya-seekha", exactText: "How can one sheet of paper become strong enough to hold something heavy?\n\nThis week, Arjun tried a simple challenge with a sheet of paper.\n\nAt first, he placed it flat and tried to put something on top of it.\n\nIt bent almost immediately.\n\nThen he changed the paper.\n\nHe folded it.\n\nHe gave it ridges.\n\nHe changed its shape and tried again.\n\nThe paper was still the same paper.\n\nBut suddenly, it could do much more than before.\n\nSometimes, what something can do depends not only on what it is — but also on how we use it.", sourceType: "locked-app-copy", sourceReference: "Founder-locked Paper Challenge website thread, 2026-09-02", approvalStatus: "approved", placement: "Home / Aaj Kya Seekha", illustrative: true },
  { id: "home-parent-summary", exactText: "Sometimes, the approach matters as much as the answer.\n\nThis week, Arjun explored a simple idea through an ordinary sheet of paper.\n\nWhen the paper stayed flat, it could only handle so much.\n\nWhen he folded and reshaped it, the result changed.\n\nThe activity was about more than making paper stronger.\n\nIt offered a small way to notice something that appears often in learning: when something isn't working, trying harder isn't always the only option.\n\nSometimes, changing the approach changes what becomes possible.", sourceType: "locked-app-copy", sourceReference: "Founder-locked Paper Challenge website thread, 2026-09-02", approvalStatus: "approved", placement: "Home / Parent Summary", illustrative: true },
  { id: "home-real-life-mein-dekho", exactText: "The same material can do very different things.\n\nLook around and you'll find this idea everywhere.\n\nA cardboard box can protect something fragile because of the way its layers are arranged.\n\nA paper cup can hold water even though paper itself seems weak.\n\nA bridge becomes strong not simply because of the material used, but because of the way the material is shaped and supported.\n\nThe material hasn't magically become something else.\n\nIts structure has changed what it can do.\n\nMaybe that is worth noticing in other parts of life too.", sourceType: "locked-app-copy", sourceReference: "Founder-locked Paper Challenge website thread, 2026-09-02", approvalStatus: "approved", placement: "Home / Real Life Mein Dekho", illustrative: true },
  { id: "home-dinner-table-conversation", exactText: "What was the most interesting thing that happened at school today that you haven’t told anyone about yet?", sourceType: "locked-app-copy", sourceReference: "Founder-approved website editorial update, 2026-09-02", approvalStatus: "approved", placement: "Home / Dinner Table Conversation", illustrative: true },
  { id: "home-worth-revisiting", exactText: "Does changing the way you approach something change what becomes possible?\n\nSometimes, changing the approach changes everything.", sourceType: "locked-app-copy", sourceReference: "Founder-locked Paper Challenge website thread, 2026-09-02", approvalStatus: "approved", placement: "Home / Worth Revisiting", illustrative: true },
] as const satisfies readonly EditorialContentRecord[];

export const canopyContent = [
  { id: "canopy-weekly-letter", exactText: "Two questions that stayed with Arjun this week\n\nThis week, Arjun spent time learning about planets and the solar system in Science.\n\nSomewhere along the way, one question followed him beyond the lesson:\n\nIf the Moon is in the sky during the day, why can't we always see it?\n\nLater in the week, something much closer to home caught his attention.\n\nHe noticed that the leaves on some trees were beginning to look different and wondered why they change colour.\n\nOne question began with something happening far above him.\n\nThe other began with something growing right outside.\n\nBut both started in the same place:\n\nArjun noticed something he had seen before—and looked at it differently this time.\n\nPerhaps that's what made these questions worth keeping.\n\nNot because they needed immediate answers.\n\nBut because something ordinary had become interesting enough to wonder about.", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Weekly Letter", illustrative: true },
  { id: "canopy-family-rhythms", exactText: "Dinner Table Conversation\nWhat was the most interesting thing that happened at school today that you haven’t told anyone about yet?\n\nDo This Together\nThe Blindfolded Halwai Taste Test\n\nPick four sweet, salty, or tangy food items from the kitchen—like a pinch of chaat masala, a drop of honey, a piece of roasted peanut, or a slice of lemon.\n\nOne person wears a blindfold and pinches their nose shut while taking a tiny bite of one item.\n\nTry to guess what it is without your sense of smell, then unpinch your nose and notice the sudden burst of flavor.\n\nSwap roles and test the other person with a new taste.\n\nIf you guess wrong, that's okay.\n\nYou'll remember discovering how much smell shapes every single bite.\n\nOne Thing Worth Talking About\nBALANCING INDEPENDENCE & ASKING FOR HELP\n\nWhen you are struggling with schoolwork, friendship drama, or low mood, why does reaching out to a parent feel like defeat?\n\nA GENTLE THOUGHT:\nBeing independent does not mean solving every crisis alone. Knowing when to ask for a hand is a sign of maturity, not helplessness.\n\nANOTHER DOOR OPENS:\n\nHow can parents make it feel safer for you to share hard things without judging?\n\nWhat stops people from admitting they are overwhelmed?\n\nAROUND THE TABLE:\n\nWhat is something you prefer handling entirely on your own now?\n\nWho is one person outside our house you feel safe confiding in?\n\nHow can we check in on each other without it feeling like an interrogation?\n\nA THOUGHT TO CARRY:\nAsking for help when you need it is a decision to stay strong.", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Family Rhythms", illustrative: true },
  { id: "canopy-curiosities", exactText: "Is there something you still enjoy doing or watching that you don't usually tell your classmates about because they might call it childish?", sourceType: "locked-app-copy", sourceReference: "Founder-locked Quiet Questions set, Hidden Hobbies, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Curiosities", illustrative: true },
  { id: "canopy-thinkers", exactText: "When an app keeps showing you funny clips one after another for an hour, what is the app actually taking from you while you watch?", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Thinkers", illustrative: true },
  { id: "canopy-create", exactText: "The Melt Test\n\nPut one ice cube on a steel plate and one on a wooden chopping board.\n\nWhich one turns to water first?\n\nAnd why does the steel feel colder if both are in the same room?", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Create", illustrative: true },
  { id: "canopy-dinner-table-conversation", exactText: "What was the most interesting thing that happened at school today that you haven’t told anyone about yet?", sourceType: "locked-app-copy", sourceReference: "Founder-approved website editorial update, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Dinner Table Conversation", illustrative: true },
  { id: "canopy-do-this-together", exactText: "The Blindfolded Halwai Taste Test\n\nPick four sweet, salty, or tangy food items from the kitchen—like a pinch of chaat masala, a drop of honey, a piece of roasted peanut, or a slice of lemon.\n\nOne person wears a blindfold and pinches their nose shut while taking a tiny bite of one item.\n\nTry to guess what it is without your sense of smell, then unpinch your nose and notice the sudden burst of flavor.\n\nSwap roles and test the other person with a new taste.\n\nIf you guess wrong, that's okay.\n\nYou'll remember discovering how much smell shapes every single bite.", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / Do This Together", illustrative: true },
  { id: "canopy-one-thing-worth-talking-about", exactText: "BALANCING INDEPENDENCE & ASKING FOR HELP\n\nWhen you are struggling with schoolwork, friendship drama, or low mood, why does reaching out to a parent feel like defeat?\n\nA GENTLE THOUGHT:\nBeing independent does not mean solving every crisis alone. Knowing when to ask for a hand is a sign of maturity, not helplessness.\n\nANOTHER DOOR OPENS:\n\nHow can parents make it feel safer for you to share hard things without judging?\n\nWhat stops people from admitting they are overwhelmed?\n\nAROUND THE TABLE:\n\nWhat is something you prefer handling entirely on your own now?\n\nWho is one person outside our house you feel safe confiding in?\n\nHow can we check in on each other without it feeling like an interrogation?\n\nA THOUGHT TO CARRY:\nAsking for help when you need it is a decision to stay strong.", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Canopy / One Thing Worth Talking About", illustrative: true },
] as const satisfies readonly EditorialContentRecord[];

export const withinContent = [
  { id: "within-patterns-over-time", exactText: "Across three different weeks, Arjun returned to questions about how light changes what we see.\n\nThe moments appeared in science, in a story, and while walking home. Together they suggest a recurring interest — not a conclusion about him.", sourceType: "founder-approved-explanatory-copy", sourceReference: "Editorial example review, 2026-09-01", approvalStatus: "approved", placement: "Within / Patterns Over Time", illustrative: true },
  { id: "within-pause", exactText: "Secrets and the Screen\n\nWhen your child tilts their screen away or quickly closes a chat window as you walk past, why does a quiet wave of panic and suspicion rise in your chest?", sourceType: "locked-app-copy", sourceReference: "Founder-locked curated website content, 2026-09-02", approvalStatus: "approved", placement: "Within / Pause", illustrative: true },
  { id: "within-just-arjun", exactText: "While packing his school bag this week, Arjun found a folded note from a classmate and smiled before placing it carefully inside his pencil case. He did not explain the note, and no explanation was needed.\n\nIt was a small moment from his week — something he chose to keep close, without anyone deciding what it must mean.", sourceType: "founder-approved-explanatory-copy", sourceReference: "Founder-directed Class 6 website refinement, 2026-09-02", approvalStatus: "approved", placement: "Within / Just Arjun", illustrative: true },
  { id: "within-moments", exactText: "On the walk home, Arjun stopped beneath a tree and said, “My shadow is walking in front of me now.”\n\nNothing needed to follow. It was simply a moment worth keeping.", sourceType: "founder-approved-explanatory-copy", sourceReference: "Editorial example review, 2026-09-01", approvalStatus: "approved", placement: "Within / Moments", illustrative: true },
  { id: "within-story-so-far", exactText: "Arjun’s questions often begin with something ordinary: a shadow, a sentence in a story, a difference he has noticed.\n\nSome return later in another form; others pass. The story so far holds both, without deciding what they must mean.", sourceType: "founder-approved-explanatory-copy", sourceReference: "Editorial example review, 2026-09-01", approvalStatus: "approved", placement: "Within / Arjun’s Story So Far", illustrative: true },
  { id: "within-story-gratitude", exactText: "Thank you for noticing what often goes unseen.", sourceType: "locked-app-copy", sourceReference: "components/product/within-reflection-card.tsx at Group 9 start", approvalStatus: "approved", placement: "Within / Arjun’s Story So Far / closing line", illustrative: false },
] as const satisfies readonly EditorialContentRecord[];
